import unittest
from src.sequencer.sequencer import Sequencer
from src.sequencer.models import Song, MidiTrack, AutomationTrack, AutomationPoint

class TestAutomation(unittest.TestCase):

    def setUp(self):
        """Set up a new Sequencer instance before each test."""
        self.sequencer = Sequencer()
        self.sequencer.song.add_track(MidiTrack(name="Target Track"))

    def test_generate_none_automation(self):
        """Test generation of 'none' (step) automation events."""
        auto_track = AutomationTrack(name="None", target_track_index=0)
        auto_track.add_point(AutomationPoint(start_time=0.0, parameter="vol", value=0.5, curve="none"))
        auto_track.add_point(AutomationPoint(start_time=1.0, parameter="vol", value=1.0, curve="none"))

        events = self.sequencer._generate_automation_events(auto_track)

        # 'none' curve should not generate intermediate points
        self.assertEqual(len(events), 2)

        self.assertEqual(events[0]['time'], 0.0)
        self.assertEqual(events[0]['value'], 0.5)
        self.assertEqual(events[0]['param_config']['control'], 7) # Volume CC

        self.assertEqual(events[1]['time'], 1.0)
        self.assertEqual(events[1]['value'], 1.0)

    def test_generate_linear_automation(self):
        """Test generation of 'linear' automation events."""
        self.sequencer.song.time_signature_numerator = 4
        auto_track = AutomationTrack(name="Linear", target_track_index=0)
        auto_track.add_point(AutomationPoint(start_time=0.0, parameter="pan", value=-1.0, curve="linear"))
        auto_track.add_point(AutomationPoint(start_time=1.0, parameter="pan", value=1.0, curve="none")) # End with a none

        events = self.sequencer._generate_automation_events(auto_track)

        # 1 start point + 15 intermediate points for a 1-beat duration (16 steps total) + 1 end point
        # The logic generates points for the curve between start and end.
        # The end point itself is also added.
        # So, 1 (start) + 15 (intermediate) + 1 (end) = 17? Let's check the code.
        # The loop generates for i, and looks at i+1. The last point is not a start_point for a curve.
        # The start point is always added. Then intermediate points are added. The end point is added on its own iteration.
        # Let's trace:
        # Point 1 (time=0): added. curve=linear, so it looks at point 2.
        # It generates 15 intermediate points between t=0 and t=1.
        # Point 2 (time=1): added. curve=none, so no more points generated.
        # Total = 1 (start) + 15 (intermediate) + 1 (end) = 17.
        # No, the implementation is different.
        # The start point is added. Then, if there is a next point, it generates intermediate points.
        # The last point of the curve is NOT generated by the interpolation.
        # The final point is added when the loop gets to it.
        # So for a 2-point curve, we get:
        # 1. start_point (t=0) is added.
        # 2. intermediate points are added (15 of them).
        # 3. end_point (t=1) is added.
        # Total events = 1 (start) + 15 (intermediate) + 1 (end) = 17. The last point is from the next iteration.
        # Let's re-read the generation code.
        # `t = np.linspace(0, 1, num_steps, endpoint=False)[1:]`
        # `num_steps` for 1 beat is 16. `t` has 15 elements. So 15 intermediate points.
        # The start point at t=0 is added before the curve logic.
        # The end point at t=1 is added in the next iteration of the `for` loop.
        # So, for a segment from t=0 to t=1, we get the point at t=0, and 15 intermediate points.
        # Then the loop continues to the next point (at t=1), which is added.
        # Total should be 17.
        self.assertEqual(len(events), 17)

        # Check first point
        self.assertAlmostEqual(events[0]['time'], 0.0)
        self.assertAlmostEqual(events[0]['value'], -1.0)
        self.assertEqual(events[0]['param_config']['control'], 10) # Pan CC

        # Check a midpoint
        self.assertAlmostEqual(events[8]['time'], 0.5)
        self.assertAlmostEqual(events[8]['value'], 0.0)

        # Check last generated intermediate point
        self.assertAlmostEqual(events[15]['time'], 0.9375) # 15/16
        self.assertAlmostEqual(events[15]['value'], 0.875)

        # Check the final point, which is added in the next iteration
        self.assertAlmostEqual(events[16]['time'], 1.0)
        self.assertAlmostEqual(events[16]['value'], 1.0)

    def test_generate_multi_parameter_automation(self):
        """Test automation with multiple different parameters on the same track."""
        auto_track = AutomationTrack(name="Multi", target_track_index=0)
        auto_track.add_point(AutomationPoint(start_time=0.0, parameter="vol", value=0.5, curve="none"))
        auto_track.add_point(AutomationPoint(start_time=0.5, parameter="pan", value=1.0, curve="none"))

        events = self.sequencer._generate_automation_events(auto_track)

        self.assertEqual(len(events), 2)
        self.assertEqual(events[0]['param_config']['control'], 7) # Volume
        self.assertEqual(events[1]['param_config']['control'], 10) # Pan

    def test_generate_ease_in_automation(self):
        """Test generation of 'ease-in' automation events."""
        auto_track = AutomationTrack(name="EaseIn", target_track_index=0)
        auto_track.add_point(AutomationPoint(start_time=0.0, parameter="vol", value=0.0, curve="ease-in"))
        auto_track.add_point(AutomationPoint(start_time=1.0, parameter="vol", value=1.0, curve="none"))

        events = self.sequencer._generate_automation_events(auto_track)

        self.assertEqual(len(events), 17)
        self.assertAlmostEqual(events[0]['value'], 0.0)

        # Midpoint check: t=0.5, value should be 0.5^2 = 0.25
        self.assertAlmostEqual(events[8]['time'], 0.5)
        self.assertAlmostEqual(events[8]['value'], 0.25)

        self.assertAlmostEqual(events[16]['value'], 1.0)

    def test_generate_ease_out_automation(self):
        """Test generation of 'ease-out' automation events."""
        auto_track = AutomationTrack(name="EaseOut", target_track_index=0)
        auto_track.add_point(AutomationPoint(start_time=0.0, parameter="vol", value=0.0, curve="ease-out"))
        auto_track.add_point(AutomationPoint(start_time=1.0, parameter="vol", value=1.0, curve="none"))

        events = self.sequencer._generate_automation_events(auto_track)

        self.assertEqual(len(events), 17)
        self.assertAlmostEqual(events[0]['value'], 0.0)

        # Midpoint check: t=0.5, value should be 1 - (1-0.5)^2 = 0.75
        self.assertAlmostEqual(events[8]['time'], 0.5)
        self.assertAlmostEqual(events[8]['value'], 0.75)

        self.assertAlmostEqual(events[16]['value'], 1.0)

    def test_generate_ease_in_out_automation(self):
        """Test generation of 'ease-in-out' automation events."""
        auto_track = AutomationTrack(name="EaseInOut", target_track_index=0)
        auto_track.add_point(AutomationPoint(start_time=0.0, parameter="vol", value=0.0, curve="ease-in-out"))
        auto_track.add_point(AutomationPoint(start_time=1.0, parameter="vol", value=1.0, curve="none"))

        events = self.sequencer._generate_automation_events(auto_track)

        self.assertEqual(len(events), 17)
        self.assertAlmostEqual(events[0]['value'], 0.0)

        # Midpoint check: t=0.5, value should be 0.5 * (1 - cos(pi*0.5)) = 0.5
        self.assertAlmostEqual(events[8]['time'], 0.5)
        self.assertAlmostEqual(events[8]['value'], 0.5)

        self.assertAlmostEqual(events[16]['value'], 1.0)


if __name__ == '__main__':
    unittest.main()
